for(const el of document.querySelectorAll(".muted"))if(el.textContent.includes("Version:"))el.textContent="Version: v0.9.29";
const C=window.CHAIN_CONFIG||{},$=s=>document.querySelector(s),S=C.sessionId||"main-chain",U=C.supabaseUrl,K=C.supabaseAnonKey,A="https://api.torn.com/v2",KS="chainQueue.tornApiKey",SS="chainQueue.sound";
let me=null,q=[],secs=null,count=0,myAttackCursor=null,lastSharedLoad=0,lastTimerSync=0,apiFails=0,lastNextId=null,audioCtx=null,tornClockOffset=0,lastTornClockSync=0,lastMinePoll=0,lastLeaderPoll=0,lastHeartbeat=0,canLead=true,errorSent=new Map(),session={leader_id:null,leader_name:null,trigger_seconds:240,paused:false,manual_hit_player_id:null,last_attack_id:null,chain_timer_seconds:null,chain_timer_synced_at:null,chain_count:0,chain_end_at:null,chain_max:0};
const fmt=n=>n==null?"--:--":Math.floor(n/60)+":"+String(Math.max(0,n%60)).padStart(2,"0"),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function soundOn(){return localStorage.getItem(SS)!=="0"}function unlockAudio(){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume()}catch{}}function setSoundButton(){let b=$("#sound");if(!b)return;b.textContent=soundOn()?"🔊 Sounds: ON":"🔇 Sounds: OFF";b.classList.toggle("on",soundOn())}function toggleSound(){localStorage.setItem(SS,soundOn()?"0":"1");setSoundButton();if(soundOn()){unlockAudio();tone("hit")}}function tone(kind){if(!soundOn())return;try{unlockAudio();let now=audioCtx.currentTime,notes=kind==="turn"?[660,880,1040]:[520,700];notes.forEach((f,i)=>{let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;g.gain.setValueAtTime(.0001,now+i*.11);g.gain.exponentialRampToValueAtTime(.12,now+i*.11+.015);g.gain.exponentialRampToValueAtTime(.0001,now+i*.11+.1);o.connect(g);g.connect(audioCtx.destination);o.start(now+i*.11);o.stop(now+i*.11+.11)})}catch{}}function say(x){$("#msg").textContent=x||""} async function req(url,opt={}){let r=await fetch(url,opt),j=null;try{j=await r.json()}catch{}if(!r.ok){let e=Error(j?.error?.message||j?.error?.error||j?.message||"HTTP "+r.status);e.code=String(j?.error?.code??j?.code??r.status);throw e}return j}
async function torn(p){let k=localStorage.getItem(KS);if(!k)throw Error("Enter a Limited API key");let j=await req(A+p,{headers:{Authorization:"ApiKey "+k}});if(j?.error){let e=Error(j.error?.error||j.error?.message||"Torn API error");e.code=String(j.error?.code??"");e.endpoint=p;throw e}return j}
async function db(path,opt={}){return req(U+"/rest/v1/"+path,{method:opt.method||"GET",headers:{apikey:K,Authorization:"Bearer "+K,"Content-Type":"application/json",Prefer:opt.prefer||"return=minimal"},body:opt.body})}
async function rpc(fn,p){return db("rpc/"+fn,{method:"POST",body:JSON.stringify(p),prefer:"return=representation"})}
function errCode(e){let m=String(e?.message||"");return String(e?.code||(/incorrect id[- ]entity relation/i.test(m)?"7":/too many requests/i.test(m)?"429":""))}
async function reportError(context,e,endpoint=""){try{let code=errCode(e),message=String(e?.message||e||"Unknown error").slice(0,240),sig=context+"|"+code+"|"+message,now=Date.now();if(now-(errorSent.get(sig)||0)<60000)return;errorSent.set(sig,now);await rpc("chain_report_error",{p_session:S,p_player_id:me?.id||null,p_version:"0.9.29",p_context:context,p_code:code||null,p_message:message,p_endpoint:endpoint||e?.endpoint||null,p_platform:"Web"})}catch{}}
function factionPermissionError(e){return errCode(e)==="7"||/incorrect id[- ]entity relation/i.test(String(e?.message||""))}
async function probeFactionApi(){try{await torn("/faction/attacks?limit=1&sort=DESC");canLead=true;return true}catch(e){if(factionPermissionError(e)){canLead=false;await reportError("Faction API permission",e,"/faction/attacks");return false}await reportError("Faction API probe",e,"/faction/attacks");return true}}
async function syncTornClock(){let sent=Date.now(),j=await torn("/faction/timestamp"),recv=Date.now(),v=j.timestamp??j.time??j.server_time??j,ts=typeof v==="object"?(v.timestamp??v.time??v.server_time):v;ts=+ts;if(!Number.isFinite(ts)||ts<=0)throw Error("Invalid Torn timestamp");if(ts<1e12)ts*=1000;tornClockOffset=ts-((sent+recv)/2);lastTornClockSync=recv}
function tornNow(){return Date.now()+tornClockOffset}
function leader(){return !!me&&+session.leader_id===me.id} function localClock(){if(session.chain_end_at!=null){secs=Math.max(0,Math.ceil((+session.chain_end_at*1000-tornNow())/1000));count=+session.chain_count||0;return}if(session.chain_timer_seconds==null||!session.chain_timer_synced_at)return;secs=Math.max(0,+session.chain_timer_seconds-Math.max(0,Math.floor((Date.now()-Date.parse(session.chain_timer_synced_at))/1000)));count=+session.chain_count||0}
async function load(){q=await db("chain_queue?session_id=eq."+S+"&select=*&order=position.asc,joined_at.asc")||[];let x=await db("chain_sessions?session_id=eq."+S+"&select=*")||[];if(x[0])session=x[0];lastSharedLoad=Date.now();localClock();render()}
async function control(a,v=null){if(!leader())return false;let r=await rpc("chain_session_control",{p_session:S,p_leader_id:me.id,p_action:a,p_value:v==null?null:String(v)});await load();return r}
async function bottom(id,name,attackId,ended=null){let changed=await rpc("chain_record_attack",{p_session:S,p_player_id:+id,p_player_name:name||"Player",p_attack_id:attackId,p_ended_at:ended?+ended:null});await load();if(changed){lastTimerSync=0;tone("hit");say((name||"Player")+" hit → chain reset"+(q.some(x=>+x.player_id===+id)?" + bottom":""))}return changed}
function rows(j){let v=j.attacks||j;return Array.isArray(v)?v:Object.values(v||{}).filter(x=>x&&typeof x==="object")} function good(a){let id=+(a.attacker?.id||a.attacker_id||0),r=a.respect_gain??a.respect;if(!id)return false;if(r!=null)return +r>0;return !/lost|stalemate|escape/i.test(a.result||"")} const aid=a=>String(a.id||a.attack_id||a.code||a.ended);
async function syncTimer(){let j=await torn("/faction/chain"),received=Date.now(),c=j.chain||j,end=+(c.end??0),ct=+(c.current??c.chain??0),t=end>0?Math.max(0,end-Math.floor(received/1000)):+(c.timeout??c.time_left??c.cooldown??0);secs=t;count=ct;lastTimerSync=received;if(leader())await control("timer_sync",t+","+ct)}
async function pollMine(){if(!me||!q.some(x=>+x.player_id===me.id)||Date.now()-lastMinePoll<6000)return;lastMinePoll=Date.now();let z=rows(await torn("/user/attacks?limit=10&sort=DESC")).filter(a=>good(a)&&+(a.attacker?.id||a.attacker_id||0)===me.id).sort((a,b)=>+(b.ended||b.timestamp||0)-+(a.ended||a.timestamp||0));if(!z.length)return;if(myAttackCursor==null){myAttackCursor=aid(z[0]);return}let ix=z.findIndex(a=>aid(a)===String(myAttackCursor));if(ix>0){for(let x of z.slice(0,ix).reverse())await bottom(me.id,me.name,aid(x),+(x.ended||x.timestamp||0)||null);myAttackCursor=aid(z[0])}else if(ix<0)myAttackCursor=aid(z[0])}
async function pollLeader(){if(!leader()||Date.now()-lastLeaderPoll<4000)return;lastLeaderPoll=Date.now();let z=rows(await torn("/faction/attacks?limit=100&sort=DESC")).filter(good).sort((a,b)=>+(b.ended||b.timestamp||0)-+(a.ended||a.timestamp||0)),cur=session.last_attack_id;if(z.length){if(!cur)await control("cursor",aid(z[0]));else{let ix=z.findIndex(a=>aid(a)===String(cur));if(ix>0){for(let x of z.slice(0,ix).reverse())await bottom(+(x.attacker?.id||x.attacker_id),x.attacker?.name||x.attacker_name,aid(x),+(x.ended||x.timestamp||0)||null)}else if(ix<0)await control("cursor",aid(z[0]))}}if(!lastTimerSync||Date.now()-lastTimerSync>=8000||!session.chain_end_at||(+session.chain_count||0)<=0||(+session.chain_end_at*1000)<tornNow()-30000)await syncTimer();if(Date.now()-lastHeartbeat>=15000){await control("heartbeat");lastHeartbeat=Date.now()}}
function pos(){return me?q.findIndex(x=>+x.player_id===me.id)+1:0} function mineDelay(){let p=pos();return leader()||p===1?2000:p&&p<=5?2000:p&&p<=20?5000:6000} function sharedDelay(){let p=pos();return leader()||p===1?2000:p&&p<=5?3000:p&&p<=20?5000:6000}
async function poll(){try{if(Date.now()-lastSharedLoad>=sharedDelay())await load();if(!lastTornClockSync||Date.now()-lastTornClockSync>=60000)try{await syncTornClock()}catch(e){await reportError("Torn clock sync",e,"/faction/timestamp")}try{await pollMine()}catch(e){await reportError("Attack sync",e,"/user/attacks");throw e}if(leader())try{await pollLeader()}catch(e){await reportError("Leader sync",e,"/faction/attacks");if(factionPermissionError(e)){canLead=false;await rpc("chain_capability",{p_session:S,p_player_id:me.id,p_can_lead:false});await load();say("Faction API permission required — Chain Lead reassigned if possible")}else throw e}apiFails=0;$("#conn").textContent="LIVE";render()}catch(e){apiFails++;$("#conn").textContent=apiFails>1?"RECONNECTING":"ERROR";say(e.message)}finally{clearTimeout(window.__cqPagePoll);window.__cqPagePoll=setTimeout(poll,mineDelay())}}
async function takeLead(){if(!me||!q.some(x=>+x.player_id===me.id))return say("Join the queue before taking lead.");if(!canLead)return say("Faction API permission required before taking Chain Lead.");if(leader())return say("You already have Chain Lead.");if(!confirm("⚠ ARE YOU SURE YOU WANT TO STEAL LEAD?\n\nCurrent leader: "+(session.leader_name||"Unknown")+"\n\nOnly do this if the current leader is AFK or having connection issues."))return;let ok=await rpc("chain_take_lead",{p_session:S,p_player_id:me.id});await load();say(ok?"You stole Chain Lead.":"Could not take Chain Lead.")}async function join(){await rpc("chain_join_v2",{p_session:S,p_player_id:me.id,p_player_name:me.name,p_can_lead:canLead});await load()} async function leave(){if(leader()&&q.length>1){say("Pass Chain Lead before leaving.");alert("You are the Chain Leader. Pass lead to another queued player first.");return}await rpc("chain_leave",{p_session:S,p_player_id:me.id});await load()}
function render(){let n=q[0],newNext=n?+n.player_id:null;if(lastNextId!==null&&newNext===me?.id&&lastNextId!==newNext)tone("turn");lastNextId=newNext;let tr=+session.trigger_seconds||240,forced=!!n&&+session.manual_hit_player_id===+n.player_id&&session.manual_hit_at,hit=!!n&&!session.paused&&((count>0&&secs>0&&secs<=tr)||forced),p=pos();$("#timer").textContent=fmt(secs);$("#chainCount").textContent=count>0?count+"/"+(+session.chain_max||"?"):"--";$("#queueCount").textContent=q.length;$("#myPos").textContent=p||"--";$("#nextName").textContent=n?n.player_name:"Nobody queued";$("#trigger").textContent="HIT @ "+fmt(tr);$("#leader").textContent=session.leader_name?"👑 Leader: "+session.leader_name:"⚠ No chain leader";$("#callout").textContent=session.paused?"⏸ Queue paused":!n?"Waiting for players":count<=0&&!forced?"Waiting for chain":hit?(me&&+n.player_id===me.id?"🔥 YOU — HIT NOW":"🔥 "+n.player_name+" — HIT NOW"):"Next hit @ "+fmt(tr);$(".hero").classList.toggle("hitnow",hit);let iq=me&&p>0;$("#join").disabled=!me||iq;$("#leave").disabled=!iq;$("#takelead").disabled=!me||!iq||leader()||!canLead;$("#queue").innerHTML=q.length?q.map((x,i)=>`<li class="${i===0?"nextrow":""}"><span class="pos">${i+1}</span><span class="name">${esc(x.player_name)}</span><span class="you">${me&&+x.player_id===me.id?"YOU":i===0?"NEXT":""}</span></li>`).join(""):'<li class="empty">No active queue yet.</li>';$("#admin").classList.toggle("hidden",!leader());$("#target").innerHTML=q.map(x=>`<option value="${+x.player_id}">${esc(x.player_name)}</option>`).join("");$("#tempo").value=String(tr);$("#pause").textContent=session.paused?"Resume":"Pause"}
async function connect(){let k=$("#apiKey").value.trim();if(!k)throw Error("Enter a Limited API key");localStorage.setItem(KS,k);let j=await torn("/user/basic"),u=j.profile||j;me={id:+(u.id||u.player_id),name:u.name};if(!me.id)throw Error("Could not identify user");$("#me").textContent=`Connected as ${me.name} [${me.id}]`;await probeFactionApi();try{await syncTornClock()}catch(e){await reportError("Torn clock sync",e,"/faction/timestamp")}await load();if(q.some(x=>+x.player_id===me.id)){await rpc("chain_capability",{p_session:S,p_player_id:me.id,p_can_lead:canLead});await load()}if(leader())await syncTimer();clearTimeout(window.__cqPagePoll);await poll()}
$("#saveKey").onclick=()=>connect().catch(e=>say(e.message));$("#takelead").onclick=()=>takeLead().catch(e=>say(e.message));setSoundButton();$("#sound").onclick=toggleSound;$("#join").onclick=()=>join().catch(e=>say(e.message));$("#leave").onclick=()=>leave().catch(e=>say(e.message));$("#tempo").onchange=()=>control("tempo",$("#tempo").value).catch(e=>say(e.message));$("#hitnow").onclick=()=>control("manual_hit").catch(e=>say(e.message));$("#pause").onclick=()=>control("toggle_pause").catch(e=>say(e.message));$("#skip").onclick=()=>rpc("chain_skip",{p_session:S,p_leader_id:me.id,p_player_id:+$("#target").value}).then(load).catch(e=>say(e.message));$("#remove").onclick=()=>{let id=+$("#target").value;if(id===me?.id){say("Pass Chain Lead before removing yourself.");alert("You are the Chain Leader. Pass lead to another queued player first.");return}if(confirm("Remove this player?"))rpc("chain_remove",{p_session:S,p_leader_id:me.id,p_player_id:id}).then(load).catch(e=>say(e.message))};$("#pass").onclick=()=>{let id=+$("#target").value,x=q.find(v=>+v.player_id===id);if(!x?.can_lead)return say((x?.player_name||"That player")+" cannot lead — faction API permission required.");if(confirm("Pass chain lead?"))rpc("chain_pass_lead",{p_session:S,p_current_leader:me.id,p_new_leader:id}).then(load).catch(e=>say(e.message))};
$("#apiKey").value=localStorage.getItem(KS)||"";load().catch(()=>{});setInterval(()=>{localClock();render()},250);if(localStorage.getItem(KS))connect().catch(e=>say(e.message));render();