// ==UserScript==
// @name Cloudy's Chain Manager
// @namespace https://github.com/gregapackard/torn-chain-queue
// @version 0.6.0
// @description Live Torn chaining rotation overlay
// @match https://www.torn.com/*
// @grant GM_xmlhttpRequest
// @connect api.torn.com
// @connect axpmotlarzmmhjggmgce.supabase.co
// @updateURL https://raw.githubusercontent.com/gregapackard/torn-chain-queue/main/chain-queue.user.js
// @downloadURL https://raw.githubusercontent.com/gregapackard/torn-chain-queue/main/chain-queue.user.js
// @run-at document-idle
// @license MIT
// ==/UserScript==
(()=>{"use strict";
const U="https://axpmotlarzmmhjggmgce.supabase.co",K="sb_publishable_hIkbXGYNCkv-Gm4aaDFxcQ_t1pX8Urw",S="main-chain",A="https://api.torn.com/v2",KS="chainQueue.tornApiKey",PS="chainQueue.pos";
let me=null,q=[],secs=null,count=0,apiFails=0,myAttackCursor=null,lastSharedLoad=0,session={leader_id:null,leader_name:null,trigger_seconds:240,paused:false,manual_hit_player_id:null,last_attack_id:null,chain_timer_seconds:null,chain_timer_synced_at:null,chain_count:0};
const $=x=>document.querySelector(x),fmt=n=>n==null?"--:--":Math.floor(n/60)+":"+String(Math.max(0,n%60)).padStart(2,"0");
const css=`#cq{position:fixed;z-index:999999;font:12px Arial;color:#ddd}#cq .bubble,#cq h3{touch-action:none}#cq input,#cq button{touch-action:auto;pointer-events:auto}#cq .bubble{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:#15171b;border:1px solid #4a505b;box-shadow:0 4px 15px #0009;color:#fff;font-weight:900;font-size:11px;cursor:grab;user-select:none}#cq.open .bubble{display:none}#cq .panel{display:none;width:230px;max-width:calc(100vw - 12px);max-height:calc(100vh - 12px);background:#15171b;border:1px solid #383c45;border-radius:9px;box-shadow:0 8px 28px #0009;overflow:auto;overscroll-behavior:contain;-webkit-overflow-scrolling:touch;box-sizing:border-box}#cq.open .panel{display:block}#cq h3{margin:0;padding:7px 9px;background:#101216;color:#fff;font-size:13px;cursor:grab;user-select:none;position:sticky;top:0;z-index:2}#cq h3 .min{float:right;cursor:pointer;padding:0 2px}.b{padding:7px}.hero{text-align:center;border:1px solid #333842;border-radius:7px;padding:5px}.hero.hit{background:#2b1518;border-color:#a72d35;color:#ff4651}.tm{font-size:23px;font-weight:900}.nx{font-size:14px;font-weight:900;margin:2px}.call{font-size:9px}.key{display:flex;gap:4px;margin:6px 0}.key input{min-width:0;flex:1;background:#0d0f12;color:#ddd;border:1px solid #363b44;border-radius:5px;padding:5px;font-size:11px}#cq button{min-height:36px;border:1px solid #59616e;border-radius:5px;padding:6px 8px;font-size:11px;font-weight:800;cursor:pointer;background:#343a44;color:#fff;text-shadow:0 1px 1px #000;box-shadow:inset 0 1px #ffffff12}#cq button:hover{background:#454d59}#cq button:disabled{opacity:.48;color:#c5c9cf;background:#24282f;cursor:default}.acts{display:flex;gap:4px;margin-bottom:5px}.list{margin:0;padding:0;list-style:none;max-height:130px;overflow:auto}.list li{display:grid;grid-template-columns:18px 1fr auto;padding:4px 1px;border-top:1px solid #292d34}.tag{font-size:8px;color:#52e2a4}.meta,.msg{font-size:9px;color:#929cab;margin-top:5px}.msg{color:#e8bd68}.admin{display:none;border-top:1px solid #30343b;margin-top:6px;padding-top:6px}.admin.on{display:block}.admin .row{display:flex;gap:4px;margin-top:4px}.admin select{min-width:0;flex:1;min-height:36px;background:#0d0f12;color:#ddd;border:1px solid #363b44;border-radius:5px;padding:4px;font-size:10px}.lead{font-size:9px;color:#e8bd68;margin-top:4px}@media(max-width:430px){#cq .panel{width:min(230px,calc(100vw - 12px))}#cq h3{font-size:12px}.admin .row{flex-wrap:wrap}.admin .row select{flex:1 1 100%;font-size:16px}#cq button{min-height:40px}.key input{font-size:16px;min-height:40px;box-sizing:border-box}}`
function place(d){let p;try{p=JSON.parse(localStorage.getItem(PS)||"null")}catch{};if(p){d.style.left=Math.max(0,Math.min(innerWidth-44,p.x))+"px";d.style.top=Math.max(0,Math.min(innerHeight-44,p.y))+"px"}else{d.style.right="12px";d.style.bottom="12px"}}
function drag(el,handle){let sx,sy,l,t,moved=false;const down=e=>{if(e.target.closest("input,button,.min"))return;if(e.button!=null&&e.button!==0)return;sx=e.clientX??e.touches?.[0]?.clientX;sy=e.clientY??e.touches?.[0]?.clientY;let r=el.getBoundingClientRect();l=r.left;t=r.top;moved=false;document.addEventListener("mousemove",move);document.addEventListener("mouseup",up);document.addEventListener("touchmove",move,{passive:false});document.addEventListener("touchend",up)};const move=e=>{let x=e.clientX??e.touches?.[0]?.clientX,y=e.clientY??e.touches?.[0]?.clientY;if(x==null)return;e.preventDefault();if(Math.abs(x-sx)+Math.abs(y-sy)>5)moved=true;el.style.right="auto";el.style.bottom="auto";el.style.left=Math.max(0,Math.min(innerWidth-el.offsetWidth,l+x-sx))+"px";el.style.top=Math.max(0,Math.min(innerHeight-el.offsetHeight,t+y-sy))+"px"};const up=()=>{document.removeEventListener("mousemove",move);document.removeEventListener("mouseup",up);document.removeEventListener("touchmove",move);document.removeEventListener("touchend",up);let r=el.getBoundingClientRect();localStorage.setItem(PS,JSON.stringify({x:r.left,y:r.top}));setTimeout(()=>moved=false,50)};handle.addEventListener("mousedown",down);handle.addEventListener("touchstart",down,{passive:true});return()=>moved}
function clampOpen(d){let r=d.getBoundingClientRect(),pad=6,x=Math.max(pad,Math.min(innerWidth-r.width-pad,r.left)),y=Math.max(pad,Math.min(innerHeight-r.height-pad,r.top));d.style.right="auto";d.style.bottom="auto";d.style.left=x+"px";d.style.top=y+"px"}
function mount(){let d=document.createElement("div");d.id="cq";d.innerHTML=`<style>${css}</style><div class="bubble" title="Chain Queue"><span class="bi">🔗</span></div><div class="panel"><h3>CLOUDY'S CHAIN MANAGER <span id="st">SETUP</span><span class="min">−</span></h3><div class="b"><div class="hero"><div class="tm">--:--</div><div class="call">Connect API</div><div class="nx">Nobody queued</div></div><div class="key"><input id="ck" type="password" placeholder="Limited API key"><button id="con">Connect</button></div><div class="acts"><button id="join" disabled>Join</button><button id="leave" disabled>Leave</button></div><ol class="list"></ol><div class="lead"></div><div class="admin"><b>👑 LEADER CONTROLS</b><div class="row"><select id="tempo"><option value="120">2:00</option><option value="150">2:30</option><option value="180">3:00</option><option value="210">3:30</option><option value="240">4:00</option><option value="270">4:30</option><option value="300">5:00</option><option value="330">5:30</option><option value="360">6:00</option></select><button id="hitnow">HIT NOW</button><button id="pause">Pause</button></div><div class="row"><select id="target"></select><button id="skip">Skip</button><button id="remove">Remove</button><button id="pass">Pass Lead</button></div></div><div class="meta"></div><div class="msg"></div></div></div>`;document.body.appendChild(d);place(d);$("#ck").value=localStorage.getItem(KS)||"";let wasDrag=drag(d,$("#cq .bubble"));drag(d,$("#cq h3"));$("#cq .bubble").onclick=()=>{if(!wasDrag()){d.classList.add("open");requestAnimationFrame(()=>clampOpen(d))}};$("#cq .min").onclick=e=>{e.stopPropagation();d.classList.remove("open");place(d)};$("#con").onclick=connect;$("#join").onclick=join;$("#leave").onclick=leave;$("#tempo").onchange=tempo;$("#hitnow").onclick=manualHit;$("#pause").onclick=togglePause;$("#skip").onclick=skip;$("#remove").onclick=removeTarget;$("#pass").onclick=passLead;render()}
function msg(x){$(".msg").textContent=x||""}
function request(url,opt={}){return new Promise((resolve,reject)=>GM_xmlhttpRequest({method:opt.method||"GET",url,headers:opt.headers||{},data:opt.body,onload:r=>{let j=null;try{j=r.responseText?JSON.parse(r.responseText):null}catch{};if(r.status<200||r.status>=300)reject(Error(j?.error?.error||j?.error?.message||"HTTP "+r.status));else resolve(j)},onerror:()=>reject(Error("Network request failed"))}))}
async function torn(p){let k=localStorage.getItem(KS);if(!k)throw Error("Enter a Limited API key");let j=await request(A+p,{headers:{Authorization:"ApiKey "+k}});if(j?.error)throw Error(j.error?.error||j.error?.message||"Torn API error");return j}
async function db(path,opt={}){return request(U+"/rest/v1/"+path,{method:opt.method||"GET",headers:{apikey:K,Authorization:"Bearer "+K,"Content-Type":"application/json",Prefer:opt.prefer||"return=minimal",...(opt.headers||{})},body:opt.body})}async function rpc(fn,p){return db("rpc/"+fn,{method:"POST",body:JSON.stringify(p),prefer:"return=representation"})}
function localClock(){if(session.chain_timer_seconds==null||!session.chain_timer_synced_at)return;let age=Math.max(0,Math.floor((Date.now()-Date.parse(session.chain_timer_synced_at))/1000));secs=Math.max(0,+session.chain_timer_seconds-age);count=+session.chain_count||0}async function load(){q=await db("chain_queue?session_id=eq."+S+"&select=*&order=position.asc,joined_at.asc",{method:"GET"})||[];let s=await db("chain_sessions?session_id=eq."+S+"&select=*",{method:"GET"})||[];if(s[0])session=s[0];lastSharedLoad=Date.now();localClock();render()}
async function control(action,value=null){if(!leader())return false;let r=await rpc("chain_session_control",{p_session:S,p_leader_id:me.id,p_action:action,p_value:value==null?null:String(value)});await load();return r}
function leader(){return !!me&&+session.leader_id===me.id}
function target(){return +($("#target")?.value||0)}
async function tempo(){if(!leader())return;let v=+$("#tempo").value;if(v<120||v>360||v%30)return;await control("tempo",v)}
async function manualHit(){if(!leader()||!q[0])return;await control("manual_hit");msg("HIT NOW sent to "+q[0].player_name)}
async function togglePause(){if(!leader())return;await control("toggle_pause")}
async function skip(){let id=target();if(!leader()||!id)return;if(!confirm("Skip this player to the bottom?"))return;await rpc("chain_skip",{p_session:S,p_leader_id:me.id,p_player_id:id});await load();msg("Player skipped")}
async function removeTarget(){let id=target();if(!leader()||!id)return;if(!confirm("Remove this player from the chain queue?"))return;await rpc("chain_remove",{p_session:S,p_leader_id:me.id,p_player_id:id});await load();msg("Removed from queue")}
async function passLead(){let id=target(),x=q.find(v=>+v.player_id===id);if(!leader()||!x)return;if(!confirm("Pass Chain Lead to "+x.player_name+"?"))return;await rpc("chain_pass_lead",{p_session:S,p_current_leader:me.id,p_new_leader:id});await load();msg("Chain lead passed to "+x.player_name)}
async function join(){if(!me)return;await rpc("chain_join",{p_session:S,p_player_id:me.id,p_player_name:me.name});await load();msg(leader()?"Joined — you are Chain Leader":"Joined")}
async function leave(){if(!me)return;if(leader()&&q.length>1&&!confirm("You are Chain Leader. Leave and hand leadership to NEXT?"))return;await rpc("chain_leave",{p_session:S,p_player_id:me.id});await load();msg("Left queue")}
async function bottom(id,name,attackId=null){let changed=await rpc("chain_move_bottom",{p_session:S,p_player_id:+id,p_attack_id:attackId});await load();if(changed)msg((name||"Player")+" hit → bottom");return changed}
function rows(j){let v=j.attacks||j;return Array.isArray(v)?v:Object.values(v||{}).filter(x=>x&&typeof x==="object")}
function good(a){let id=+(a.attacker?.id||a.attacker_id||0),r=a.respect_gain??a.respect;if(!id)return false;if(r!=null)return +r>0;return !/lost|stalemate|escape/i.test(a.result||"")}
async function syncTimer(){let j=await torn("/faction/chain"),c=j.chain||j,t=+(c.timeout??c.time_left??c.cooldown??0),ct=+(c.current??c.chain??0);secs=t;count=ct;if(leader())await control("timer_sync",t+","+ct);return {t,ct}}
function mine(a){return +(a.attacker?.id||a.attacker_id||0)===me?.id}
async function pollMine(){if(!me||!q.some(x=>+x.player_id===me.id))return;let z=rows(await torn("/user/attacks?limit=10&sort=DESC")).filter(a=>good(a)&&mine(a)).sort((a,b)=>+(b.ended||b.timestamp||0)-+(a.ended||a.timestamp||0)),aid=a=>String(a.id||a.attack_id||a.code||a.ended);if(!z.length)return;if(myAttackCursor==null){myAttackCursor=aid(z[0]);return}let ix=z.findIndex(a=>aid(a)===String(myAttackCursor));if(ix>0){for(let x of z.slice(0,ix).reverse())await bottom(me.id,me.name,aid(x));myAttackCursor=aid(z[0])}else if(ix<0)myAttackCursor=aid(z[0])}
async function pollLeader(){if(!leader())return;let z=rows(await torn("/faction/attacks?limit=20&sort=DESC")).filter(good).sort((a,b)=>+(b.ended||b.timestamp||0)-+(a.ended||a.timestamp||0)),aid=a=>String(a.id||a.attack_id||a.code||a.ended),cursor=session.last_attack_id,hitSeen=false;if(z.length){if(!cursor){await control("cursor",aid(z[0]))}else{let ix=z.findIndex(a=>aid(a)===String(cursor));if(ix>0){for(let x of z.slice(0,ix).reverse()){hitSeen=true;let pid=+(x.attacker?.id||x.attacker_id);await bottom(pid,x.attacker?.name||x.attacker_name,aid(x))}}else if(ix<0){await control("cursor",aid(z[0]));hitSeen=true;msg("Attack cursor resynced")}}if(hitSeen)await syncTimer()}await control("heartbeat")}
function myPos(){return me?q.findIndex(x=>+x.player_id===me.id)+1:0}
function mineDelay(){let p=myPos();return leader()||p===1?1250:p>0&&p<=5?2000:p>0&&p<=20?5000:6000}
function sharedDelay(){let p=myPos();return leader()||p===1?2000:p>0&&p<=5?3000:p>0&&p<=20?5000:6000}
async function pollFast(){try{if(Date.now()-lastSharedLoad>=sharedDelay())await load();await pollMine();if(leader())await pollLeader();localClock();apiFails=0;$("#st").textContent="LIVE";render()}catch(e){apiFails++;$("#st").textContent=apiFails>1?"RECONNECTING":"ERROR";msg("Connection issue — retrying automatically");localClock();render()}finally{clearTimeout(window.__cqFast);window.__cqFast=setTimeout(pollFast,mineDelay())}}
async function connect(){try{let k=$("#ck").value.trim();if(!k)throw Error("Enter a Limited API key");localStorage.setItem(KS,k);let j=await torn("/user/basic"),u=j.profile||j;me={id:+(u.id||u.player_id),name:u.name};if(!me.id)throw Error("Could not identify user");await load();if(leader())await syncTimer();else if(session.chain_timer_synced_at)localClock();clearTimeout(window.__cqFast);clearInterval(window.__cqClock);await pollFast();window.__cqClock=setInterval(()=>{localClock();render()},250);msg("Connected")}catch(e){msg(e.message)}}
function render(){if(!$("#cq"))return;let n=q[0],tr=+session.trigger_seconds||240,forced=!!n&&+session.manual_hit_player_id===+n.player_id&&session.manual_hit_at,hit=!!n&&!session.paused&&((count>0&&secs>0&&secs<=tr)||forced);$(".tm").textContent=fmt(secs);$(".nx").textContent=n?n.player_name:"Nobody queued";$(".call").textContent=session.paused?"⏸ Queue paused":!n?"Waiting for players":count<=0&&!forced?"Waiting for chain":hit?(me&&+n.player_id===me.id?"🔥 YOU — HIT NOW":"🔥 "+n.player_name+" — HIT NOW"):"Next hit @ "+fmt(tr);$(".hero").classList.toggle("hit",hit);let iq=me&&q.some(x=>+x.player_id===me.id);$("#join").disabled=!me||iq;$("#leave").disabled=!iq;let pace=Math.max(0,300-tr),eta=i=>i===0?"NOW":"~"+Math.ceil(i*pace/60)+"m";$(".list").innerHTML=q.length?q.map((x,i)=>`<li><span>${i+1}</span><b>${String(x.player_name).replace(/[<>]/g,"")}</b><span class="tag">${me&&+x.player_id===me.id?"YOU • "+eta(i):i===0?"NEXT • NOW":eta(i)}</span></li>`).join(""):"<li><span>—</span><span>No active queue</span><span></span></li>";$(".lead").textContent=session.leader_name?"👑 Leader: "+session.leader_name:"⚠ No chain leader";$(".admin").classList.toggle("on",leader());$("#target").innerHTML=q.map(x=>`<option value="${+x.player_id}">${String(x.player_name).replace(/[<>]/g,"")}</option>`).join("");$("#tempo").value=String(tr);$("#pause").textContent=session.paused?"Resume":"Pause";$(".meta").textContent="Chain: "+count+(me?" • "+me.name:"");let pos=me?q.findIndex(x=>+x.player_id===me.id)+1:0,b=$(".bi");if(b){if(n&&me&&+n.player_id===me.id&&hit)b.textContent="🔥";else if(count>0&&secs>0&&secs<=30)b.textContent="⚠️";else if(pos)b.textContent=String(pos);else b.textContent="🔗"}if(count>0&&secs>0&&secs<=60&&!session.paused&&!hit)$(".call").textContent="⚠️ "+fmt(secs)+" — chain getting low"}
mount();load().catch(()=>{});if(localStorage.getItem(KS))connect();
})();