// ==UserScript==
// @name Cloudy's Chain Manager
// @namespace https://github.com/gregapackard/torn-chain-queue
// @version 0.4.1
// @description Live Torn chaining rotation overlay
// @match https://www.torn.com/*
// @grant GM_xmlhttpRequest
// @connect api.torn.com
// @connect axpmotlarzmmhjggmgce.supabase.co
// @updateURL https://raw.githubusercontent.com/gregapackard/torn-chain-queue/main/chain-queue.user.js
// @downloadURL https://raw.githubusercontent.com/gregapackard/torn-chain-queue/main/chain-queue.user.js
// @run-at document-idle
// @license MIT
// ==/UserScript==
(()=>{"use strict";
const U="https://axpmotlarzmmhjggmgce.supabase.co",K="sb_publishable_hIkbXGYNCkv-Gm4aaDFxcQ_t1pX8Urw",S="main-chain",A="https://api.torn.com/v2",KS="chainQueue.tornApiKey",PS="chainQueue.pos";
let me=null,q=[],secs=null,count=0,last=null,session={leader_id:null,leader_name:null,trigger_seconds:240,paused:false,manual_hit_player_id:null};
const $=x=>document.querySelector(x),fmt=n=>n==null?"--:--":Math.floor(n/60)+":"+String(Math.max(0,n%60)).padStart(2,"0");
const css=`#cq{position:fixed;z-index:999999;font:12px Arial;color:#ddd}#cq .bubble,#cq h3{touch-action:none}#cq input,#cq button{touch-action:auto;pointer-events:auto}#cq .bubble{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:#15171b;border:1px solid #4a505b;box-shadow:0 4px 15px #0009;color:#fff;font-weight:900;font-size:11px;cursor:grab;user-select:none}#cq.open .bubble{display:none}#cq .panel{display:none;width:230px;background:#15171b;border:1px solid #383c45;border-radius:9px;box-shadow:0 8px 28px #0009;overflow:hidden}#cq.open .panel{display:block}#cq h3{margin:0;padding:7px 9px;background:#101216;color:#fff;font-size:13px;cursor:grab;user-select:none}#cq h3 .min{float:right;cursor:pointer;padding:0 2px}.b{padding:7px}.hero{text-align:center;border:1px solid #333842;border-radius:7px;padding:5px}.hero.hit{background:#2b1518;border-color:#a72d35;color:#ff4651}.tm{font-size:23px;font-weight:900}.nx{font-size:14px;font-weight:900;margin:2px}.call{font-size:9px}.key{display:flex;gap:4px;margin:6px 0}.key input{min-width:0;flex:1;background:#0d0f12;color:#ddd;border:1px solid #363b44;border-radius:5px;padding:5px;font-size:11px}#cq button{border:0;border-radius:5px;padding:5px 7px;font-size:11px;font-weight:700;cursor:pointer}#cq button:disabled{opacity:.4}.acts{display:flex;gap:4px;margin-bottom:5px}.list{margin:0;padding:0;list-style:none;max-height:130px;overflow:auto}.list li{display:grid;grid-template-columns:18px 1fr auto;padding:4px 1px;border-top:1px solid #292d34}.tag{font-size:8px;color:#52e2a4}.meta,.msg{font-size:9px;color:#929cab;margin-top:5px}.msg{color:#e8bd68}.admin{display:none;border-top:1px solid #30343b;margin-top:6px;padding-top:6px}.admin.on{display:block}.admin .row{display:flex;gap:4px;margin-top:4px}.admin select{min-width:0;flex:1;background:#0d0f12;color:#ddd;border:1px solid #363b44;border-radius:5px;padding:4px;font-size:10px}.lead{font-size:9px;color:#e8bd68;margin-top:4px}`
function place(d){let p;try{p=JSON.parse(localStorage.getItem(PS)||"null")}catch{};if(p){d.style.left=Math.max(0,Math.min(innerWidth-44,p.x))+"px";d.style.top=Math.max(0,Math.min(innerHeight-44,p.y))+"px"}else{d.style.right="12px";d.style.bottom="12px"}}
function drag(el,handle){let sx,sy,l,t,moved=false;const down=e=>{if(e.target.closest("input,button,.min"))return;if(e.button!=null&&e.button!==0)return;sx=e.clientX??e.touches?.[0]?.clientX;sy=e.clientY??e.touches?.[0]?.clientY;let r=el.getBoundingClientRect();l=r.left;t=r.top;moved=false;document.addEventListener("mousemove",move);document.addEventListener("mouseup",up);document.addEventListener("touchmove",move,{passive:false});document.addEventListener("touchend",up)};const move=e=>{let x=e.clientX??e.touches?.[0]?.clientX,y=e.clientY??e.touches?.[0]?.clientY;if(x==null)return;e.preventDefault();if(Math.abs(x-sx)+Math.abs(y-sy)>5)moved=true;el.style.right="auto";el.style.bottom="auto";el.style.left=Math.max(0,Math.min(innerWidth-el.offsetWidth,l+x-sx))+"px";el.style.top=Math.max(0,Math.min(innerHeight-el.offsetHeight,t+y-sy))+"px"};const up=()=>{document.removeEventListener("mousemove",move);document.removeEventListener("mouseup",up);document.removeEventListener("touchmove",move);document.removeEventListener("touchend",up);let r=el.getBoundingClientRect();localStorage.setItem(PS,JSON.stringify({x:r.left,y:r.top}));setTimeout(()=>moved=false,50)};handle.addEventListener("mousedown",down);handle.addEventListener("touchstart",down,{passive:true});return()=>moved}
function mount(){let d=document.createElement("div");d.id="cq";d.innerHTML=`<style>${css}</style><div class="bubble" title="Chain Queue">🔗</div><div class="panel"><h3>CLOUDY'S CHAIN MANAGER <span id="st">SETUP</span><span class="min">−</span></h3><div class="b"><div class="hero"><div class="tm">--:--</div><div class="call">Connect API</div><div class="nx">Nobody queued</div></div><div class="key"><input id="ck" type="password" placeholder="Limited API key"><button id="con">Connect</button></div><div class="acts"><button id="join" disabled>Join</button><button id="leave" disabled>Leave</button></div><ol class="list"></ol><div class="lead"></div><div class="admin"><b>👑 LEADER CONTROLS</b><div class="row"><button id="tempo">Tempo: 4:00</button><button id="hitnow">HIT NOW</button><button id="pause">Pause</button></div><div class="row"><select id="target"></select><button id="skip">Skip</button><button id="remove">Remove</button><button id="pass">Pass Lead</button></div></div><div class="meta"></div><div class="msg"></div></div></div>`;document.body.appendChild(d);place(d);$("#ck").value=localStorage.getItem(KS)||"";let wasDrag=drag(d,$("#cq .bubble"));drag(d,$("#cq h3"));$("#cq .bubble").onclick=()=>{if(!wasDrag())d.classList.add("open")};$("#cq .min").onclick=e=>{e.stopPropagation();d.classList.remove("open")};$("#con").onclick=connect;$("#join").onclick=join;$("#leave").onclick=leave;$("#tempo").onclick=tempo;$("#hitnow").onclick=manualHit;$("#pause").onclick=togglePause;$("#skip").onclick=skip;$("#remove").onclick=removeTarget;$("#pass").onclick=passLead;render()}
function msg(x){$(".msg").textContent=x||""}
function request(url,opt={}){return new Promise((resolve,reject)=>GM_xmlhttpRequest({method:opt.method||"GET",url,headers:opt.headers||{},data:opt.body,onload:r=>{let j=null;try{j=r.responseText?JSON.parse(r.responseText):null}catch{};if(r.status<200||r.status>=300)reject(Error(j?.error?.error||j?.error?.message||"HTTP "+r.status));else resolve(j)},onerror:()=>reject(Error("Network request failed"))}))}
async function torn(p){let k=localStorage.getItem(KS);if(!k)throw Error("Enter a Limited API key");let j=await request(A+p,{headers:{Authorization:"ApiKey "+k}});if(j?.error)throw Error(j.error?.error||j.error?.message||"Torn API error");return j}
async function db(path,opt={}){return request(U+"/rest/v1/"+path,{method:opt.method||"GET",headers:{apikey:K,Authorization:"Bearer "+K,"Content-Type":"application/json",Prefer:opt.prefer||"return=minimal",...(opt.headers||{})},body:opt.body})}
async function load(){q=await db("chain_queue?session_id=eq."+S+"&select=*&order=position.asc,joined_at.asc",{method:"GET"})||[];let s=await db("chain_sessions?session_id=eq."+S+"&select=*",{method:"GET"})||[];if(s[0])session=s[0];render()}
async function saveSession(p){await db("chain_sessions?session_id=eq."+S,{method:"PATCH",body:JSON.stringify({...p,updated_at:new Date().toISOString()})});await load()}
function leader(){return !!me&&+session.leader_id===me.id}
function target(){return +($("#target")?.value||0)}
async function tempo(){if(!leader())return;let vals=[360,240,120],cur=+session.trigger_seconds||240,i=vals.indexOf(cur);await saveSession({trigger_seconds:vals[(i+1)%vals.length]})}
async function manualHit(){if(!leader()||!q[0])return;await saveSession({manual_hit_player_id:+q[0].player_id,manual_hit_at:new Date().toISOString()});msg("HIT NOW sent to "+q[0].player_name)}
async function togglePause(){if(!leader())return;await saveSession({paused:!session.paused})}
async function skip(){let id=target();if(!leader()||!id)return;let x=q.find(v=>+v.player_id===id);if(x)await bottom(id,x.player_name)}
async function removeTarget(){let id=target();if(!leader()||!id)return;await db("chain_queue?session_id=eq."+S+"&player_id=eq."+id,{method:"DELETE"});await load();msg("Removed from queue")}
async function passLead(){let id=target(),x=q.find(v=>+v.player_id===id);if(!leader()||!x)return;await saveSession({leader_id:+x.player_id,leader_name:x.player_name,leader_heartbeat_at:new Date().toISOString()});msg("Chain lead passed to "+x.player_name)}
async function join(){await load();if(q.some(x=>+x.player_id===me.id))return;let first=q.length===0,m=q.reduce((a,x)=>Math.max(a,+x.position||0),0);await db("chain_queue",{method:"POST",body:JSON.stringify({session_id:S,player_id:me.id,player_name:me.name,position:m+1}),prefer:"resolution=merge-duplicates,return=minimal"});if(first||!session.leader_id)await saveSession({leader_id:me.id,leader_name:me.name,leader_heartbeat_at:new Date().toISOString()});else await load();msg(first?"Joined — you are Chain Leader":"Joined")}
async function leave(){let wasLeader=leader();await db("chain_queue?session_id=eq."+S+"&player_id=eq."+me.id,{method:"DELETE"});await load();if(q.length===0)await saveSession({leader_id:null,leader_name:null,leader_heartbeat_at:null,manual_hit_player_id:null,manual_hit_at:null,paused:false});else if(wasLeader)await saveSession({leader_id:+q[0].player_id,leader_name:q[0].player_name,leader_heartbeat_at:null});msg("Left queue")}
async function bottom(id,name){await load();let row=q.find(x=>+x.player_id===+id);if(!row)return;let m=q.reduce((a,x)=>Math.max(a,+x.position||0),0);await db("chain_queue?session_id=eq."+S+"&player_id=eq."+id,{method:"PATCH",body:JSON.stringify({position:m+1,last_hit_at:new Date().toISOString()})});await load();msg((name||row.player_name)+" hit → bottom")}
function rows(j){let v=j.attacks||j;return Array.isArray(v)?v:Object.values(v||{}).filter(x=>x&&typeof x==="object")}
function good(a){let id=+(a.attacker?.id||a.attacker_id||0),r=a.respect_gain??a.respect;if(!id)return false;if(r!=null)return +r>0;return !/lost|stalemate|escape/i.test(a.result||"")}
async function poll(){try{let j=await torn("/faction/chain"),c=j.chain||j;secs=+(c.timeout??c.time_left??c.cooldown??0);count=+(c.current??c.chain??0);let z=leader()?rows(await torn("/faction/attacks?limit=20&sort=DESC")).filter(good):[].sort((a,b)=>+(b.ended||b.timestamp||0)-+(a.ended||a.timestamp||0)),id=a=>String(a.id||a.attack_id||a.code||a.ended);if(z.length){let n=id(z[0]);if(last===null)last=n;else if(n!==last){let u=[];for(let a of z){if(id(a)===last)break;u.push(a)}last=n;for(let a of u.reverse()){let pid=+(a.attacker?.id||a.attacker_id);if(q.some(x=>+x.player_id===pid))await bottom(pid,a.attacker?.name||a.attacker_name)}}}if(leader())await db("chain_sessions?session_id=eq."+S,{method:"PATCH",body:JSON.stringify({leader_heartbeat_at:new Date().toISOString()})});$("#st").textContent="LIVE";render()}catch(e){$("#st").textContent="ERROR";msg(e.message)}}
async function connect(){try{let k=$("#ck").value.trim();if(!k)throw Error("Enter a Limited API key");localStorage.setItem(KS,k);let j=await torn("/user/basic"),u=j.profile||j;me={id:+(u.id||u.player_id),name:u.name};if(!me.id)throw Error("Could not identify user");await load();await poll();clearInterval(window.__cq1);clearInterval(window.__cq2);window.__cq1=setInterval(poll,5000);window.__cq2=setInterval(()=>load().catch(()=>{}),3000);msg("Connected")}catch(e){msg(e.message)}}
function render(){if(!$("#cq"))return;let n=q[0],tr=+session.trigger_seconds||240,forced=!!n&&+session.manual_hit_player_id===+n.player_id&&session.manual_hit_at,hit=!!n&&!session.paused&&((count>0&&secs>0&&secs<=tr)||forced);$(".tm").textContent=fmt(secs);$(".nx").textContent=n?n.player_name:"Nobody queued";$(".call").textContent=session.paused?"⏸ Queue paused":!n?"Waiting for players":count<=0&&!forced?"Waiting for chain":hit?(me&&+n.player_id===me.id?"🔥 YOU — HIT NOW":"🔥 "+n.player_name+" — HIT NOW"):"Next hit @ "+fmt(tr);$(".hero").classList.toggle("hit",hit);let iq=me&&q.some(x=>+x.player_id===me.id);$("#join").disabled=!me||iq;$("#leave").disabled=!iq;$(".list").innerHTML=q.length?q.map((x,i)=>`<li><span>${i+1}</span><b>${String(x.player_name).replace(/[<>]/g,"")}</b><span class="tag">${me&&+x.player_id===me.id?"YOU":i===0?"NEXT":""}</span></li>`).join(""):"<li><span>—</span><span>No active queue</span><span></span></li>";$(".lead").textContent=session.leader_name?"👑 Leader: "+session.leader_name:"⚠ No chain leader";$(".admin").classList.toggle("on",leader());$("#target").innerHTML=q.map(x=>`<option value="${+x.player_id}">${String(x.player_name).replace(/[<>]/g,"")}</option>`).join("");$("#tempo").textContent="Tempo: "+fmt(tr);$("#pause").textContent=session.paused?"Resume":"Pause";$(".meta").textContent="Chain: "+count+(me?" • "+me.name:"")}
mount();load().catch(()=>{});if(localStorage.getItem(KS))connect();
})();